[workspace]
members = [
    "mos6502",
]

[package]
name = "snes-rusty"
version = "0.1.0"
edition = "2024"

[package.metadata.leptos]
# Tells cargo-leptos where to find your assets
assets-dir = "public" 
[dependencies]
lazy_static = "1.4.0" # Or the latest version
mos6502 = { path = "./mos6502"}

bitflags = "1.2.1"
# sdl2 ="0.34.0" 
rand = "=0.7.3"
leptos = { version = "0.8.3", features = ["csr"] }
wasm-bindgen = "0.2"
web-sys = { version = "0.3", features = ["HtmlCanvasElement", "CanvasRenderingContext2d", "ImageData", "Window"] }
console_log = { version = "1.0"}
# [target.'cfg(not(target_arch = "wasm32"))'.dependencies]
# sdl2 ="0.34.0" # Moves SDL2 exclusively to desktop/native targets
